### PR TITLE
Feature - Create store selectors (projects)

### PR DESCRIPTION
**Pull request by cedric-matheus**
- Rename projects store module
- Create actions module and rename action types
- Move and rename projects actions module
- Move and rename projects reducer module
- Create projects type def
- Create projects initial state module
- Create projects store module
- Create projects actions store module readme
- Create projects reducer store module readme
- Create projects store module readme
- Create store module readme
- Create store type def
- Rename projects reducer function
- Rename project store reducer
- Create projects store selectors module
- Unify project and projects action types module
- Create projects store loading state
- Remove projects table loading state from ui store
- Create get is loading projects store selector
- Connect loading state to new projects loading
- Remove projects table loading actions from ui
- Remove projects table loading from action types
- Create fetch paginated projects action types
- Apply async pattern to fetch paginated projects
- Remove unused fetch projects action
- Apply async pattern to delete projects action
- Remove unused delete project action
- Add await to rectify bug
- Remove unused code
- Add loading rule to project actions
- Add all async actions to projects reducer
- Remove unused code
- Refactor projects store to use payload pattern
- Rectify comments
- Remove fetch projects from delete projects action
- Remove duplicated delete projects action
- Rectify delete projects action success message
- Add api model reference to projects type def
- Remove unused projects service requests
- Add projects service api reference
- Create models module
- Rectify header projects details container
- Remove export of fail and success projects actions
- Remove unused projects store reducers
- Create project updatable type def
- Adjust projects initial state
- Change edit project action type to update project
- Remove unused reducers
- Update reducers to use update project action type
- Create update project action
- Update containers to use update project action
- Rectify projects api
- Remove unused actions
- Add models module readme
- Move fetch project action to new projects store
- Update containers import
- Refactor fetch project action
- Remove unused reducers
- Refactor projects reducer
- Rectify get project selector
- Rectify fetch project request action
- Add deployments to project on get project selector
- Update containers to use get project selector
- Remove unused reducer
- Rectify update project success action
- Rectify containers to fetch project correctly
- Create project creatable model
- Rectify projects api
- Rectify projects reducer
- Move create project request to new projects store
- Update containers to use new create project action
- Remove unused actions
- Remove old project reducer
- Remove project name loading from ui store
- Update containers to use get is loading selector
- Remove project edit name loading from ui store
- Update container to use get is loading selector
- Rectify delete action
- Move fetch project logic to project details

### CODE REVIEW

**Comment by schafferjrdev** [comment]
@cedric-matheus Tem alguns smells para corrigir

**Comment by cedric-matheus** [comment]
REVIEW CHANGES

- Clear code smells
- Rectify eslint warnings
- Add project rules to readme
- Rename module folders to lowercase
- Simplify projects store
- Remove useless comments
- Rectify action types
- Rectify reducer bug
- Rectify actions to use history
- Rectify actions to use history
- Rectify containers to use hooks
- Rename projects files
- Remove unused states
- Rectify bugs
- Remove hocs and add hooks
- Remove loading responsability from projects store
- Rename projects action types to project types
- Add loading store to project actions
- Add use is loading hook
- Add message store to projects actions
- Rectify create project bug
- Remove duplicated code

**Review by fberanizo — CHANGES_REQUESTED** [review]
@cedric-matheus quando tentei importar um arquivo na caxinha de Upload aconteceu o seguinte erro:
image

Pode dar uma olhada, por favor?
O teste foi no ambiente .40

**Comment by cedric-matheus** [comment]
> @cedric-matheus quando tentei importar um arquivo na caxinha de Upload aconteceu o seguinte erro:
> image
> 
> Pode dar uma olhada, por favor?
> O teste foi no ambiente .40

Corrigido :)

**Review by fberanizo — APPROVED** [review]

**Pull request merged**
