### PR TITLE
Fix - Improve Performance

### PR DESCRIPTION
**Pull request by LuanEdCosta**
- Use useMemo for values inside a component that need something from state or props
- Move standalone variables to outside of the component (variables that don't use anything from the component, such as props, state variables or functions)
-  Create the useDeepEqualSelector hook that uses the lodash.isEqual function to check if the useSelector should return a new value
- Fix the experiment page lag by using the useDeepEqualSelector
- Improve style guide files and components readability by organizing the imports, component props and propTypes
- Remove unused components, old files and unnecessary comments

**SORRY FOR THIS HUGE PR, BUT IT SOLVES A BIG PROBLEM**
Review TIp: If you ignore the markdown files you can do it faster

### CODE REVIEW

**Review by schafferjrdev — CHANGES_REQUESTED** [review]

**Review by schafferjrdev — APPROVED** [review]
Ok

**Comment by LuanEdCosta** [comment]
Dei mais uma revisada nos arquivos e encontrei só duas coisas erradas, que não são bugs, mas já fiz os commits que corrigem estes detalhes. :+1:

**Review by fberanizo — CHANGES_REQUESTED** [review]
@LuanEdCosta como essa alteração acabou com todos arquivos de teste o yarn test:ci deu o erro abaixo. E o sonar também deu erro por consequência (não achou os resutados dos testes).
image

Eu não sei se o `--passWithNoTests` resolve pro sonar... podemos tentar.
Caso não funcione, o jeito vai se deixar pelo menos 1 arquivo de testes.

**Comment by schafferjrdev** [comment]
> SonarCloud Quality Gate failed.
> 
> [Bug](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=457&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=457&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=457&resolved=false&types=BUG)
> [Vulnerability](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=457&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=457&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=457&resolved=false&types=VULNERABILITY)
> [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=platiagro_web-ui&pullRequest=457&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=platiagro_web-ui&pullRequest=457&resolved=false&types=SECURITY_HOTSPOT) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=platiagro_web-ui&pullRequest=457&resolved=false&types=SECURITY_HOTSPOT)
> [Code Smell](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=457&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=457&resolved=false&types=CODE_SMELL) [2 Code Smells](https://sonarcloud.io/project/issues?id=platiagro_web-ui&pullRequest=457&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=457&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=457&metric=new_coverage&view=list)
> [](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=457&metric=new_duplicated_lines_density&view=list) [2.5% Duplication](https://sonarcloud.io/component_measures?id=platiagro_web-ui&pullRequest=457&metric=new_duplicated_lines_density&view=list)

O smell que tem é aqueles de complexidade, faz parte de código antigo @fberanizo pode opinar melhor, mas acho que pode passar ele.

**Pull request merged**
